### ISSUE TITLE
There is a version for Vue?

### ISSUE THREAD

**Issue by paulocoutinhox** [ardeora/solid-toast#17]
Hi,

First, nice library.

There is a version for Vue?

Thanks.

**Comment by ardeora** [comment]
Hey there! Thanks for your compliments. This library is compatible with SolidJS currently. The core itself is mostly framework agnostic but it might need some changes to make it available for other frameworks. I currently dont have any plans on working on this feature. But if there is more interest I would love to take a look at it. Thanks!

**Comment by paulocoutinhox** [comment]
Nice! It is very polished and will be nice if we have a Vue version. Anyway, thanks.
