### ISSUE TITLE
LoaderIcon parsing failure under 1.5

### ISSUE THREAD

**Issue by jchatard** [ardeora/solid-toast#20]
Hi, I'm using Solid-start alpha 101 which bundles Solid 1.5.x.

Importing the Toaster component fails with this message:

```
[plugin:vite:import-analysis] Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.

/Users/jchatard/Desktop/toast/node_modules/solid-toast/dist/source/components/LoaderIcon.jsx:5:12
3  |      <path fill="none" stroke={props.secondary || '#4b5563'} stroke-width="4" stroke-linecap="round" stroke-miterlimit="10" d="M16,6c3,0,5.7,1.3,7.5,3.4c0.6,0.7,1.1,1.4,1.5,2.2">
4  |        <animateTransform attributeName="transform" type="rotate" from="0 16 16" to="360 16 16" dur="0.75s" repeatCount="indefinite"/>
5  |      </path>
   |             ^
6  |    </svg>);
```

Seems like it's complaining about the SVG, structure...

You can try here: https://stackblitz.com/github/jchatard/solid-toast-parse-issue?file=src%2Froutes%2Findex.tsx
Repro repo here: https://github.com/jchatard/solid-toast-parse-issue

Thank a bunch!
Jérémy

**Comment by ardeora** [comment]
Thank you so much for bringing up this issue :D Yeah I could reproduce it on my end as well. I believe it had an older solid js version in its dependencies which was causing Vite to get angry. I was able to push `v0.3.5` which takes care of this issue. Here is your solid start demo working now https://stackblitz.com/edit/github-3h4qah?file=src%2Fcomponents%2FCounter.tsx Please let me know if you still face any issues 😄

**Comment by jchatard** [comment]
Awesome :-)

Thank you!
