### ISSUE TITLE
Big custom icons are not centered in toast

### ISSUE THREAD

**Issue by Xarib** [ardeora/solid-toast#3]
Custom JSX icons are currently size constrained by 20x20 and that causes issues with aligning.

Example:
![example](https://user-images.githubusercontent.com/67692366/174371613-aba7e071-4dce-4bb4-bf57-b3f1d883ef87.png)

Code:
```typescript
toast("example", {
  icon: <div style={{
    "height": "30px",
    "width": "30px",
    "border-radius": "50%",
    "background-color": "red",
  }}/>,
});
```

**Comment by ardeora** [comment]
Thanks for pointing out this issue. Yeah seems like icon sizing could be made more dynamic. I'll push an update to fix this issue tonight 😄

**Comment by ardeora** [comment]
Okay so I have the fix applied and it is published on an alpha branch. You can test it out here.
https://stackblitz.com/edit/vitejs-vite-y39ydn?file=src/App.tsx

Let me know if this works for you too and I will publish it to the main prod version

**Comment by Xarib** [comment]
Thanks for the fast work 🙏. Tested it both in stackblitz and locally. Works without issues.
