### ISSUE TITLE
[SSR] `y.template is not a function`

### ISSUE THREAD

**Issue by m4rvr** [ardeora/solid-toast#6]
Hey! I'm using solid-toast with Astro and I'm getting `y.template is not a function` when using it. 
It seems like a common problem if the library isn't SSR compatible.

IIRC it's recommended to ship Solid libraries with preserved JSX so the bundler can decide which build (client or server) to use.

Any chance to get this implemented? Maybe bundling with `rollup-preset-solid`?

**Comment by m4rvr** [comment]
This would be great, thanks! :)

**Comment by m4rvr** [comment]
@ardeora I've just created a PR #7 which solves this. I tried it locally with solid-start and it works without errors. Maybe the double quotes in the `rollup.config.js` need to be replaced with single quotes. I would've done it but my auto-format settings in VSCode made it impossible since you don't have any prettier config in the repo. 😂

**Comment by ardeora** [comment]
Hey Marvin! I have merged your changes and it seems like these changes allow us to work with SSR frameworks although you would still need to set `ssr.noExternal: ['solid-toast']` for now. I think this behaviour is expected. We can also revisit this later as Astro and solid-start mature more. I will close this issue for now and mark it as complete
