### ISSUE TITLE
Using the toast in an Effect causes infinite loop

### ISSUE THREAD

**Issue by edelmeier** [ardeora/solid-toast#60]
I am trying to throw a toast when certain data constellations occur. This is handled in an effect.  Unfortunately, calling the `toast` functionality from within an effect causes infinite loops in the effect.

See this fork:
https://stackblitz.com/edit/vitejs-vite-yy5ned?file=src%2FApp.tsx

**Comment by ardeora** [comment]
I'm not really sure why a toast needs to be created inside an effect 😅 Solid toast updates a solid store when a new toast is created and using that inside an effect creates a cyclic loop. You can opt out of reactive tracking of the toast store by using the `untrack` keyword. Example shown here https://stackblitz.com/edit/vitejs-vite-nrvxuy?file=src%2FApp.tsx

**Comment by ardeora** [comment]
Alternatively, the `on` function can be used here to explicitly track your dependencies

**Comment by ardeora** [comment]
Please let me know if you run into any issues other and I would be glad to help out 😁

**Comment by edelmeier** [comment]
Thanks for your reply, I tried the `untrack` approach and it works fine. 
Nevertheless, I really wonder why you say calling from an effect is unusual way of doing it. I haven't seen a declarative way to create and style the `toast` - that's why I have to do it in the effect.

Please look at the following:
```
 <Toaster position="top-center" >
   <Toast condition={condition1() && condition2()} style="error" configuration={ duration: Infinity }>
</Toaster>
```

If this were possible, I wouldn't have to imperatively call `toast.error(...)` in my effect (condition1 and condition2 are true after data has been loaded).
I hope I have been able to clarify the issue.

**Comment by ardeora** [comment]
Haha I apologize for this. I think you're right. Usually, toasts should be called from within event handlers or after a mutation/query completes. But that should not prevent users from using it within an effect too. I have pushed solid-toast v0.4.0 that should fix the infinite loop issue and you wouldn't need to use `unwrap` now. Let me know if you face any other issues. Hope you have a happy holiday

**Comment by ardeora** [comment]
Here is the example for reference https://stackblitz.com/edit/vitejs-vite-gewldq?file=src%2FApp.tsx
