### ISSUE TITLE
Problem with new `moduleResolution: bundler` (Typescript 5.0)

### ISSUE THREAD

**Issue by nathanbabcock** [ardeora/solid-toast#82]
I noticed this error after adding `"moduleResolution": "bundler"` in my `tsconfig.json`.

![solid-toast-module-resolution-bundler](https://user-images.githubusercontent.com/9583103/226204591-7759ce2c-b127-4701-bebc-2129c4392052.png)

I don't fully understand the error message, but I found an easy way to fix it by modifying `node_modules/solid-toast/package.json`. If I add this line, the error instantly goes away:

```diff
  "exports": {
    ".": {
+      "types": "./dist/types/index.d.ts",
      "solid": "./dist/source/index.jsx",
      "import": "./dist/esm/index.js",
      "browser": "./dist/esm/index.js",
      "require": "./dist/cjs/index.js",
      "node": "./dist/cjs/index.js"
    }
  },
```

I'll put it in a PR if this seems like the proper fix.

**Comment by ardeora** [comment]
Hello! Thank you so much for bringing this issue to light 😄  Yeah a PR would be really helpful! Also, I'm trying to follow the best practices from the solid-lib-starter repo so if we can update the package.json in this format https://github.com/solidjs-community/solid-lib-starter/blob/main/package.json#L26-L43 and confirm that things still work. I will merge this in a heartbeat!

**Comment by nathanbabcock** [comment]
On it.
