### ISSUE TITLE
Headless version available?

### ISSUE THREAD

**Issue by whytspace** [ardeora/solid-toast#93]
This is not a bug report, it's more of a question.

Is there any chance to get a headless (= zero styles) version of this plugin?
Maybe by making the contents of [`/src/core`](https://github.com/ardeora/solid-toast/tree/main/src/core) available to use?

**Comment by ardeora** [comment]
Hello! Yes! You can fully customize the toast in a headless mode. Here is how you can provide your custom elements and styling 

```tsx
// Custom JSX Toast
toast.custom((t) => (
	<div 
		class="px-6 py-3 pr-12 bg-white rounded-full shadow-md font-medium relative">
			Custom JSX Content
		<button 
			class="bg-gray-200/80 hover:bg-gray-300 flex justify-center top-1/2 -translate-y-1/2 items-center w-6 h-6 right-2.5 absolute rounded-full"
			onClick={() => toast.dismiss(t.id)}
		>
				&times;
		</button>
	</div>
), {
	duration: 6000, 
	unmountDelay: 0
})
```

Please let me know if you run into any issues!

**Comment by whytspace** [comment]
@ardeora Thanks for the explanation. Sorry, my question was not precise enough.
I was trying to change the Toaster, not the Toast itself. 

Specifically I wanted to use a different way of positioning the toasts (not each individually) but the container itself and the toasts just relative (or static) inside. My idea was to just create my own <Toaster> component based on the existing one. You are using soime helper functions in there that I would like to resue for my own toaster. But I cannot import them from the core.
