### ISSUE TITLE
Long text will not split/wrap if there are not spaces in the message

### ISSUE THREAD

**Issue by Juranamou** [ardeora/solid-toast#99]
![image](https://github.com/ardeora/solid-toast/assets/77448750/4b5b9f20-e303-420b-af54-26028acf74c4)

**Comment by WayeeeZ** [comment]
`<Toaster
        containerStyle={{
          'word-break': 'break-all',
        }}
      />`

**Comment by Juranamou** [comment]
Hey thanks big dog
